# r-consortium-proposal
Application for https://www.r-consortium.org/projects/call-for-proposals



# R Consortium Proposal: School of Data Material Development

[Heidi Seibold](http://www.ebpi.uzh.ch/en/aboutus/departments/biostatistics/teambiostats/seibold.html),
[Camila Salazar](),
[David Opoku](),
[Cedric Lombion]()

## The Problem
R has great tools for accessing and analysing open data sources, which would be
hugely beneficial to journalists.  However there is a low level of awareness of
R in the journalism community and specialized courses -- especially in
languages other than English -- are not available.

Journalists can profit from data skills because they allow them to access
diverse data, do more profound research and communicate through visualisations.

There are many introductory R courses for a broad audience and we are planning
to build ontop of them, i.e., do the basic introduction with available material
(e.g. [swirl](http://swirlstats.com/)) and and beyond this use specialised
material for journalists, which still needs to be developed. In order to be
able to tailor material for the needs of journalists we sent out a survey to
journalists all over the world to assess what those needs are.


## The Plan

- Use lessons already available (e.g. [swirl](http://swirlstats.com/),
  [existing school of data tutorials](http://www.datactivi.st/IntroR_ODF/)).
If needed, translate material.
- Buil ontop of these tutorials to address focus groups (CSOs and journalists
  in different countries) with focused material including relevant data sets,
techniques and repositories to make code and results freely available.
- Make all material available to use and develop further or adjust for
  different focus groups (e.g. via GitHub).

<!-- TODO: 
- timeline
- What are likely failure modes and how will you recover from them?
-->


## How Can The ISC Help?

- Financially by supporting salary of material developers and teachers.
- Financially by paying for travel costs of teachers and workshop rooms to
  organize workshops in Ghana, Costa Rica, France and Switzerland.

<!-- TODO: What do we predict, one workshop will cost? Including salary, travel
costs and room rent? -->

## Dissemination

